'use strict';

const field = (key, label, required = true) => ({ key, label, required });

module.exports = {
  suit: { note: 'Final collar measurements should be plus 1.5"/2" to the actual measurement.', fields: [field('fabricColor', 'Fabric Color'), field('suitStyle', 'Suit Style'), field('gender', 'Gender'), field('lapelFabric', 'Lapel Fabric'), field('lapelStyle', 'Lapel Style'), field('lapelWidth', 'Lapel Width'), field('pocketStyle', 'Pocket Style'), field('ventStyle', 'Vent Style'), field('collarType', 'Collar Type'), field('sbDb', 'SB/DB'), field('sleeveType', 'Sleeve Type'), field('handKnitting', 'Hand Knitting'), field('buttonStyle', 'Button Style'), field('additionalInformation', 'Additional Information', false)] },
  native: { note: 'Chest pocket depth, 7". Chest pocket height should be plus 1.5" to the width. Final neck measurements should be plus 1.5" to the actual measurement.', fields: [field('fabricColor', 'Fabric Color'), field('neckType', 'Neck Type'), field('length', 'Length'), field('sleeveType', 'Sleeve Type'), field('cuffType', 'Cuff Type'), field('chestPocketStyle', 'Chest Pocket Style'), field('collarType', 'Collar Type'), field('embroidery', 'Embroidery'), field('embroideryType', 'Embroidery Type'), field('collarButton', 'Collar Button'), field('twifLogo', 'Twif Logo'), field('buttonType', 'Button Type'), field('liningType', 'Lining Type'), field('collarSize', 'Collar Size'), field('longSleeveType', 'Long Sleeve Type'), field('slitType', 'Slit Type'), field('slitLiningType', 'Slit Lining Type'), field('sidePocket', 'Side Pocket'), field('cap', 'Cap'), field('capStyle', 'Cap Style'), field('additionalInformation', 'Additional Information', false)] },
  shirts: { note: 'Kids cuff must be button not cufflinks. Final collar measurements should be plus 1.5" to the actual measurement.', fields: [field('fabricColor', 'Fabric Color'), field('gender', 'Gender'), field('buttonHoleStand', 'Button Hole Stand'), field('sleeveType', 'Sleeve Type'), field('longSleeveType', 'Long Sleeve Type'), field('cuffStyle', 'Cuff Style'), field('cuffType', 'Cuff Type'), field('collar', 'Collar'), field('collarSize', 'Collar Size'), field('embroidery', 'Embroidery'), field('embroideryType', 'Embroidery Type'), field('collarThickness', 'Collar Thickness'), field('shirtEnd', 'Shirt End'), field('beadingEmbellishment', 'Beading/Embellishment'), field('buttonType', 'Button Type'), field('additionalInformation', 'Additional Information', false)] },
  agbada: { note: '', fields: [field('fabricColor', 'Fabric Color'), field('agbadaStyle', 'Agbada Style'), field('sleeveType', 'Sleeve Type'), field('embroideryType', 'Embroidery Type'), field('sleeveLining', 'Sleeve Lining'), field('additionalInformation', 'Additional Information', false)] },
  design: { note: '', fields: [field('fabricType', 'Fabric Type'), field('fabricColor', 'Fabric Color'), field('threadColor', 'Thread Color'), field('embroideryLength', 'Embroidery Length'), field('danshiki', 'Danshiki'), field('trouser', 'Trouser'), field('cap', 'Cap'), field('additionalInformation', 'Additional Information', false)] },
  pants: { note: 'Trousers for kids (age 0-13) must have elastic on the band at the back.', fields: [field('fabricColor', 'Fabric Color'), field('pantType', 'Pant Type'), field('gender', 'Gender'), field('pleats', 'Pleats'), field('bandStyle', 'Band Style'), field('bandExtension', 'Band Extension'), field('bandSize', 'Band Size'), field('beltlessType', 'Beltless Type'), field('sideStripe', 'Side Stripe'), field('backPocketStyle', 'Back Pocket Style'), field('additionalInformation', 'Additional Information', false)] },
};
